kind: pipeline
name: default
type: docker

clone: 
  disable: true
platform:
  os: windows
  arch: amd64
  version: 1809
  
trigger:
  event:
    include:
      - push
      - promote
 
image_pull_secrets:
- dockerconfig

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: subgit

  commands:
  - ls
  - git clone $subgit
 

    
