kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- ghdkjson 

steps:
- name: fetch
  image: alpine/git

  commands:
  #- git fetch --tags
 
  - git clone --recursive https://github.com/uNetworking/uWebSockets.js.git source
  - git clone -b others https://github.com/tomasky/drones others
  - cp others/build.c source/
  
- name: build
  image: i386/alpine:3.13
  commands:
  - cd source ;pwd
  - apk update
  - apk add alpine-sdk build-base clang   cmake perl openssl-dev libunwind-dev go llvm  
  - ln -sf /usr/lib/llvm10/lib/LLVMgold.so /usr/lib/LLVMgold.so
  - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
  - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.34-r0/glibc-2.34-r0.apk
  - apk add glibc-2.34-r0.apk
   
  - make


- name: publish
  #image: docker.pkg.github.com/tomasky/drone-github-release/master:latest
  image: plugins/github-release
  settings:
    #overwrite:
    #note: 
    #repo: 
    api_key:
      from_secret: gh_token
    files:  source/dist/*.node
  when:
    event: tag
