kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- dockerconfig

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: gradgit

  commands:
  #- git fetch --tags
  - git clone $subgit source
  
- name: test
  image: gradle 
  commands:
  - cd source
  - gradle assembleDebug
