kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- ghdkjson 

steps:
- name: fetch
  image: alpine/git

  commands:
  #- git fetch --tags
  - git clone https://github.com/neovim/neovim source
  - git clone -b neov https://github.com/tomasky/drones some
   
- name: build macos
  image: sickcodes/docker-osx:high-sierra
  commands:
  - sudo chmod 777 source
  - cd source
  - git --version;uname
  - wget https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  - sed -i 's/SUPPORTED="10.15"/SUPPORTED="10.13"/g' install.sh
  - sed -i 's/REQUIRED_GIT_VERSION=2.7.0/REQUIRED_GIT_VERSION=2.34.1/g' install.sh
  - bash install.sh
  - brew update >/dev/null
  - brew install automake ninja
  - printf 'NVIM_BUILD_TYPE=Release\n' >> $GITHUB_ENV
  - make CMAKE_BUILD_TYPE=${NVIM_BUILD_TYPE} CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH= -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9"
  - make DESTDIR="build/source/release/nvim-osx64" install

  - sh ../some/buildmac.sh

 
     
- name: publish
  #image: docker.pkg.github.com/tomasky/drone-github-release/master:latest
  image: plugins/github-release
  settings:
    #overwrite:
    #note: 
    #repo: 
    api_key:
      from_secret: gh_token
    files: 
    - source/build/source/release/nvim-*.tar.gz
  when:
    event: tag
