kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - push
      - promote
 
image_pull_secrets:
- dockerconfig
matrix:
  IMAGE:
    - dockcross/linux-x86
    # - dockcross/android-arm64

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: subgit

  commands:
  #- git fetch --tags
  - wget https://nim-lang.org/download/nim-1.6.6-linux_x64.tar.xz && tar xvf nim-1.6.6*
  - git clone https://github.com/nim-lang/nimble out

    
- name: build-x86
  image: dockcross/linux-x86
  commands:
  - export PATH=$PWD/nim-1.6.6/bin:$PATH && cd out
  - echo $CC 
  - nimble build
  - nimble build --cc:env
  - file nimble    
