kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- labdkjson 

steps:
- name: fetch
  image: alpine/git

  commands:
  #- git fetch --tags
  - git clone https://github.com/neovim/neovim source
  
- name: build
  image: i386/ubuntu:16.04
  commands:
  - cd source
  - sudo apt-get update -y
  - sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip -y
  - make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/local/nvim install
  - cd $HOME/local && tar cfz nvim-master.tar.gz nvim


- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: gh_token
    files: $HOME/local/nvim-master.tar.gz
  when:
    event: tag
