kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    - tag
    - push
    - promote
    - cron

image_pull_secrets:
- ghdkjson 

steps:
- name: fetch
  image: alpine/git

  commands:
  #- git fetch --tags
  - git clone --depth=1 https://github.com/neovim/neovim source
  #- git clone -b neov https://github.com/tomasky/drones 
  
- name: build x86
  image: i386/ubuntu:18.04
  commands:
  - cd source
  - apt-get update -y
  - apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip git -y
  - make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=source/nvim install
  - cd build/source && tar cfz nvim-master.tar.gz nvim

 
     
- name: publish
  #image: docker.pkg.github.com/tomasky/drone-github-release/master:latest
  image: plugins/github-release
  settings:
    #overwrite:
    #note: 
    #repo: 
    api_key:
      from_secret: gh_token
    files: 
    - source/build/source/nvim-master.tar.gz
  when:
    event: 
      - tag
      - cron

