kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- ghdkjson 

steps:
- name: fetch
  image: alpine/git

  commands:
  #- git fetch --tags
  - git clone https://github.com/neovim/neovim source
  
- name: build x86
  image: i386/ubuntu:18.04
  commands:
  - cd source
  - apt-get update -y
  - apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip -y
  - make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=source/nvim install
  - cd build/source && tar cfz nvim-master.tar.gz nvim

- name: build macos10.13
  image: macos:10.13
  commands: 
  - >
    bash -s <<SCRIPT
      cd source
      brew update >/dev/null
      brew install automake ninja
      printf 'NVIM_BUILD_TYPE=Release\n' >> $GITHUB_ENV
      make CMAKE_BUILD_TYPE=${NVIM_BUILD_TYPE} CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH= -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13"
      make DESTDIR="build/source/release/nvim-osx64" install
  
          cd "build/source/release"
          mkdir -p nvim-osx64/libs
          libs=($(otool -L nvim-osx64/bin/nvim | sed 1d | sed -E -e 's|^[[:space:]]*||' -e 's| .*||'))
          echo "libs:"
          for lib in "${libs[@]}"; do
            if echo "$lib" | grep -q -E 'libSystem|CoreFoundation' 2>/dev/null; then
              echo "  [skipped] $lib"
            else
              echo "  $lib"
              relname="libs/${lib##*/}"
              cp -L "$lib" "nvim-osx64/$relname"
              install_name_tool -change "$lib" "@executable_path/../$relname" nvim-osx64/bin/nvim
            fi
          done
          tar cfz nvim-macos.tar.gz nvim-osx64
          
    SCRIPT
- name: publish
  #image: docker.pkg.github.com/tomasky/drone-github-release/master:latest
  image: plugins/github-release
  settings:
    #overwrite:
    #note: 
    #repo: 
    api_key:
      from_secret: gh_token
    files: 
    - source/build/source/nvim-master.tar.gz
    - source/build/source/release/nvim-macos.tar.gz
  when:
    event: tag
