kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- dockerconfig

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: sbtgit

  commands:
  #- git fetch --tags
  - git clone $subgit source
  
- name: test
  image: jianann/alpine-clang
  commands:
  - cd source
  - sh install.sh
    
   
