kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- ghdkjson

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: gradgit

  commands:
  #- git fetch --tags
  - git clone $subgit source
  
- name: test
  image: registry.gitlab.com/weezway/dkpkgs:android 
  commands:
  - cd source
  - gradle assembleDebug
  when:
    event: main

- name: publish
  image: docker.pkg.github.com/tomasky/drone-github-release/main:master 
  settings:
    repo: scalandk
    api_key:
      from_secret: gh_token
    files: source/app/build.gradle
