kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- labdkjson 

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: gradgit

  commands:
  #- git fetch --tags
  - git clone $subgit source
  
- name: test
  image: registry.gitlab.com/weezway/dkpkgs:android 
  commands:
  - cd source
  - gradle assembleDebug

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: gh_token
    files: source/app/build/outputs/apk/debug/app-debug.apk
  when:
    event: tag
