kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- ghdkjson 

steps:
- name: fetch
  image: alpine/git

  commands:
  #- git fetch --tags
 
  - git clone --recursive https://github.com/uNetworking/uWebSockets.js.git source
  
- name: build
  image: i386/alpine:3.13
  commands:
  - cd source ;pwd
  - apk update
  - apk add alpine-sdk build-base clang libc6-compat cmake
  
  - make


- name: publish
  #image: docker.pkg.github.com/tomasky/drone-github-release/master:latest
  image: plugins/github-release
  settings:
    #overwrite:
    #note: 
    #repo: 
    api_key:
      from_secret: gh_token
    files:  source/dist/*.node
  when:
    event: tag
