kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- dockerconfig

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: sbtgit

  commands:
  #- git fetch --tags
  - git clone $subgit source
  
- name: test
  image: amaya382/scala-native-builder 
  commands:
  - cd source
  - apk update && apk add curl
  - curl -o some.apk https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/clang-9.0.0-r1.apk
  - apk add some.apk
  - sbt run 
    
   
