kind: pipeline
name: default
type: docker

clone: 
  git: 
    image: plugins/git 
    tags: true

steps:
 
- name: test
  image: hayd/alpine-deno:1.4.6
  environment:
    subgit:
      from_secret: subgit

  commands:
  - apk add git 
  - git clone $subgit
  - deno --version
  - cd denok && deno cache main.ts
    
- name: publish
  image: plugins/docker
  
  settings:
    auto_tag: true
    auto_tag_suffix: latest
    dockerfile: ./denok/Dockerfile
    context: ./denok
    repo: registry.gitlab.com/weezway/deno-https-server
    registry: registry.gitlab.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    
- name: pull
  image: registry.gitlab.com/weezway/deno-https-server
  commands:
    - ls -l
    - deno --version

 
image_pull_secrets:
- dockerconfig
