kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
# - dockerconfig
# - ghdkjson
- labdkjson

steps:
- name: fetch
  image: alpine/git
  environment:
    subgit:
      from_secret: sbtgit

  commands:
  #- git fetch --tags
  - git clone $subgit source
  
- name: test
  image: registry.gitlab.com/weezway/dkpkgs:master
  commands:
  - cd source
  - sbt run

- name: test2
  image: alpine:latest
  when:
    event:
      - tag
  commands:
  - cd source
  - apk update
  - apk add --no-cache openjdk8
  - apk --no-cache add clang clang-dev gc-dev musl-dev libc-dev build-base git
  - apk add libunwind-dev re2 -U -X http://nl.alpinelinux.org/alpine/edge/main

  - export SBT_VERSION="1.5.5"
  - export SBT_HOME="/usr/local/sbt"
  - export PATH="$PATH:$SBT_HOME/bin"
  - mkdir -p $SBT_HOME
  - apk add --no-cache bash wget bc
  - wget "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" -O - | tar xz -C $SBT_HOME --strip-components=1
  - sbt run


