kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  event:
    include:
      - tag
      - push
      - promote
 
image_pull_secrets:
- ghdkjson 

steps:
- name: fetch
  image: alpine/git

  commands:
  #- git fetch --tags
  - git clone --recursive https://github.com/uNetworking/uWebSockets.js.git source
  
- name: build
  image: i386/ubuntu:16.04
  commands:
  - cd source
  - apt-get update -y
  - apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip clang -y
  - make


- name: publish
  #image: docker.pkg.github.com/tomasky/drone-github-release/master:latest
  image: plugins/github-release
  settings:
    #overwrite:
    #note: 
    #repo: 
    api_key:
      from_secret: gh_token
    files: dist/*.node
  when:
    event: tag
