kind: pipeline
name: default
type: docker

clone: 
  disable: true
 
trigger:
  branch:
    - deno
    - master
  event:
    include:
      - push
      - promote
 
 
image_pull_secrets:
- dockerconfig

steps:
- name: fetch
  image: alpine/git
  environment:
    registry:
      from_secret: registry
    subgit:
      from_secret: subgit
  commands:
  #- git fetch --tags
  - git clone $subgit
  
- name: test
  image: hayd/alpine-deno:1.4.6
  commands:
  - deno --version
  - cd denok && deno cache main.ts
    
- name: publish
  image: plugins/docker
  
  settings:
    auto_tag: true
    auto_tag_suffix: latest
    dockerfile: ./denok/Dockerfile
    context: ./denok
    repo:  $registry
    registry: registry.gitlab.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

    
- name: pull
  image: registry.gitlab.com/$registry
  commands:
    - ls -l /app
    - deno --version

