kind: pipeline
name: default
type: docker

clone: 
  git: 
    image: plugins/git 
    tags: true
    environment:
      subgit:
        from_secret: subgit
      DRONE_REMOTE_URL=$subgit

steps:
 
- name: test
  image: hayd/alpine-deno:1.4.6
  environment:
    subgit:
      from_secret: subgit
    regs:
      from_secret: regs

  commands:
  - mkdir -p $HOME/.docker/
  - ls -l $HOME
  - echo $${regs} > $HOME/.docker/config.json
  - ls -l $HOME/.docker/config.json
  - apk add git 
  - git clone $subgit
  - deno --version
  - cd denok && deno cache main.ts
    
- name: publish
  image: plugins/docker
  
  settings:
    auto_tag: true
    auto_tag_suffix: latest
    dockerfile: ./denok/Dockerfile
    context: ./denok
    repo: registry.gitlab.com/weezway/deno-https-server
    registry: registry.gitlab.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    
- name: build
  image: registry.gitlab.com/weezway/deno-https-server
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
image_pull_secrets:
- regs
